R/descriptives.R, tests/figs/Descriptives/descriptives-qqplot.svg, tests/figs/jasp-deps.txt
part I of https://github.com/jasp-stats/jasp-issues/issues/1096
the main changes are:
- properly set the limits, before one point was removed from the figure for e.g., contNormal.
- the y-axis title is now "sample quantiles", similar to base R.
=> improve qq plot

R/descriptives.R, inst/qml/Descriptives.qml
Hey, I created an Intervalplot for our SKF project and it would be nice to have that implemented in Descriptives.
=> Intervalplot

R/descriptives.R, inst/qml/Descriptives.qml
Fixes jasp-stats/INTERNAL-jasp#1054
-Adding bin width options (Sturges, Scott, Doane, Freedman-Diaconis, Manual) to histogram.
-Add options for rug tick marks.
=> HistogramBinWidthAndRugs

R/descriptives.R, inst/help/descriptives.md, inst/qml/Descriptives.qml
Fixes https://github.com/jasp-stats/jasp-issues/issues/1084
Just a simple addtion of the coefficient of variation to descriptives.
=> added the coefficient of variation

.Rbuildignore, .github/workflows/unittests.yml, .gitignore, tests/figs/Descriptives/descriptives-boxplot.svg
`ggrepel` changed things so I had to recreate one figure. I think it actually looks a bit better now though.
=> update everything for r4

R/descriptives.R, tests/figs/Descriptives/descriptives-facgender.svg, tests/figs/jasp-deps.txt, tests/testthat/test-descriptives.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1281
Also adds a unit test for the discrete distribution plots.
=> Increase top margin for discrete distribution plots & add a unit test

.github/workflows/unittests.yml, R/descriptives.R, tests/testthat/_snaps/descriptives/dotplot.svg
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1406
Before:
After:
=> Dot plots x-axis: specify breaks and limits

R/descriptives.R, tests/testthat/_snaps/descriptives/interval-plot-across-facfive-contexpon.svg, tests/testthat/test-descriptives.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/1422 and adds a unit test.
=> Fix interval plots and add a unit test

inst/help/descriptives.md, inst/help/descriptives_nl.md
It took me a while but I finally wrote some help on the stem and leaf tables (now I only have to create the gif :stuck_out_tongue:).
=> Update docs on stem and leaf tables

R/descriptives.R, inst/qml/Descriptives.qml
Fixes https://github.com/jasp-stats/jasp-issues/issues/1060
The heatmaps do not look that good with the palettes that are currently implemented in jaspGraphs, but that can be perhaps solved later.
I also have a question about column encoding, see the comment.
=> Tile plots (Heatmaps)

inst/qml/Descriptives.qml
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1738
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1737
=> restructure descriptives input panel

DESCRIPTION, R/descriptives.R, inst/help/Descriptives.md, inst/help/Descriptives_nl.md
This PR is a minor cleanup. We use `stringr` in one place and it's quite a heavy dependency (`stringr` depends on `stringi` which takes a while to compile). Dropping this dependency should not have any short term benefits as we still use `stringr` in other places (even though there are lighter alternatives) but we have to start somewhere :man_shrugging: 
The base R function does not use the same algorithm but the results are practically the same. Here is an example:
``` r
thanks_path <- file.path(R.home("doc"), "THANKS")
thanks <- stringr::str_c(readLines(thanks_path), collapse = "\n")
thanks <- stringr::word(thanks, 1, 3, stringr::fixed("\n\n"))
cat(thanks)
#> R would not be what it is today without the invaluable help of these
#> people outside of the (former and current) R Core team, …
```
=> Drop `stringr` as dependency in favor of base R function `strwrap`

inst/qml/Descriptives.qml
I accidentally added a checkbox twice... sorry!
=> Accidentially double checkbox

R/descriptives.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2206
=> fix ci for mean and other cis

DESCRIPTION, R/descriptives.R, inst/Description.qml, inst/Upgrades.qml
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2256
=> fix heatmaps

inst/Upgrades.qml
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2302
=> Make sure heatmapLegend rename is only done if missing

inst/qml/Descriptives.qml
Requires: https://github.com/jasp-stats/jasp-desktop/pull/5188
=> use `ColorPalette{}` widgete

R/descriptives.R, tests/testthat/_snaps/descriptives/likplot.svg, tests/testthat/test-descriptives.R
fixes https://github.com/jasp-stats/jasp-issues/issues/2251
=> Fix likert levels

R/descriptives.R, inst/help/Descriptives.md, inst/help/Descriptives_de.md, inst/help/Descriptives_nl.md, inst/qml/Descriptives.qml, tests/testthat/test-descriptives.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/2288
Even if approved this should not be merged (as it shouldn't be included in the upcoming hotfix).
=> add new option for CI of the mean + update documentation

R/descriptives.R, po/R-de.po, po/R-eo.po, po/R-es.po, po/R-eu.po, po/R-fr.po, po/R-gl.po, po/R-hr.po, po/R-ja.po, po/R-jaspDescriptives.pot, po/R-nl.po, po/R-pl.po, po/R-pt.po, po/R-ru.po, po/R-zh_Hans.po, po/R-zh_Hant.po
Fixes https://github.com/jasp-stats/jasp-issues/issues/2591
=> "discreet" -> "discrete"

inst/qml/common/FlexplotForm.qml, inst/qml/raincloudPlots.qml
Needs https://github.com/jasp-stats/jasp-desktop/pull/5483
=> Generate Flexplot analysis help from info properties.

inst/qml/Descriptives.qml
Needs https://github.com/jasp-stats/jasp-desktop/pull/5520 first.
Fix: https://github.com/jasp-stats/INTERNAL-jasp/issues/2530
also use `$` delimiters for less `\\\\`
=> Revert LaTeX last changes

R/raincloudPlots.R, inst/qml/raincloudPlots.qml
Make it more consistent with the other JASP error bar plots
=> Raincloud: change SD to SE for interval option

R/commonTimeSeries.R, R/descriptives.R, R/raincloudPlots.R, inst/qml/Descriptives.qml, inst/qml/common/DescriptivesTimeSeriesForm.qml, inst/qml/raincloudPlots.qml, tests/testthat/test-descriptives.R, tests/testthat/test-raincloudPlots.R, tests/testthat/test-verified-descriptives.R
Requires https://github.com/jasp-stats/jaspBase/pull/151
=> Changes for data reading

R/raincloudPlots.R
also add check for a factor when id is specified (is possible when doing it in certain order)
=> raincloud - no lines when no points

inst/qml/common/FlexplotForm.qml
fix https://github.com/jasp-stats/jasp-test-release/issues/2666
thanks to @tomtomme 's very keen eyes!
=> flexplot: change se to ci

R/descriptives.R
fix https://github.com/jasp-stats/jasp-test-release/issues/2660
=> cov matrix only uses scale

NEWS.md, R/descriptives.R, inst/qml/Descriptives.qml, tests/testthat/test-descriptives.R
Implemented chi-squared method to calculate confidence intervals for std. dev. and variance in descriptives.
=> Chi square method to calculate var and std dev CIs

R/descriptives.R, R/raincloudPlots.R, inst/Description.qml, tests/testthat/test-descriptives.R
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2668
Fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/2677
=> fix unit tests and make raincloudPlots preload data.

R/commonTimeSeries.R, inst/Description.qml, renv.lock, tests/testthat/_snaps/DescriptivesTimeSeries/autocorrelation-function.svg, tests/testthat/_snaps/DescriptivesTimeSeries/lag-plot-subplot-1.svg, tests/testthat/_snaps/DescriptivesTimeSeries/partial-autocorrelation-function.svg, tests/testthat/_snaps/DescriptivesTimeSeries/time-series-plot-desc-subplot-1.svg, tests/testthat/test-DescriptivesTimeSeries.R
Change the is.null() and load to end data set set-up to preloaded data set
=> Update data pre-processing

inst/qml/raincloudPlots.qml
@njudd asked to add the ggrain doi to the citation in the raincloud plots analysis info
=> added doi for ggrain citation

R/commonTimeSeries.R
Fixing time series data read in and date variable detection.
Opening module crashed analysis because the options object's dependent column was empty. Further, Date variable crashed analysis, as it was loaded in as factor. Changed it so that it detects most common date types.
=> fix time series data read in

inst/qml/raincloudPlots.qml
I noticed that some translators accidentally broke the link structure, this will help to improve the link integrity in this way.
=> better links in translation strings

R/raincloudPlots.R, inst/qml/raincloudPlots.qml, tests/testthat/test-raincloudPlots.R
Fix https://github.com/jasp-stats/jasp-issues/issues/3066
=> add sd as option for raincloud plots

R/raincloudPlots.R
Fix https://github.com/jasp-stats/jasp-issues/issues/3319#issuecomment-2922786853
=> Update summarySEwithin() call for raincloud plots

R/descriptives.R
Fix https://github.com/jasp-stats/jasp-test-release/issues/2954
Fix https://github.com/jasp-stats/jasp-test-release/issues/2953
=> More error checks descriptives

R/jaspPlotBuilder.R
- fix p values on RM plot
- adding a series of p values requires the top padding of the y axis to increase with each p value added
=> Plot builder3
