R/descriptives.R, inst/qml/Descriptives.qml, tests/testthat/test-descriptives.R
Fixes one part of jasp-stats/jasp-issues#684 and implements stem and leaf tables. Dot plots will be implemented in another PR.
Sequel of https://github.com/jasp-stats/jasp-desktop/pull/4273/files
Example:
=> Implement stem and leaf tables

R/descriptives.R, inst/qml/Descriptives.qml
Fixes https://github.com/jasp-stats/jasp-issues/issues/647
If someone really wants to they can get frequency tables variables with many distinct values:
If all variables exceed the maximum number of distinct values a dummy table with footnote is shown:
If some but not all variables exceed the maximum number of distinct values a footnote is shown in the first table:
=> new option: maximum distinct values for frequency tables

inst/qml/Descriptives.qml
I that only ``titles`` should have all words capitalized
(brought to me by EJ)
=> proper capitalization of labels in historgrams

R/descriptives.R, inst/qml/Descriptives.qml
Fixes https://github.com/jasp-stats/jasp-issues/issues/1219
adds a checkbox 
so that you can get the table also in a much more space-efficient long-format. Top is old, bottom is new:
I'm not sure why the footnotes are different, I think something goes wrong with jaspResults there.
=> Added a checkbox to transpose the main table

DESCRIPTION, R/descriptives.R, inst/Description.qml, inst/help/descriptives.md, inst/qml/Descriptives.qml
Apparently I cannot change a name of a function  like "percentileValues" without breaking everything, so I reverted that and also gave the conflicts another try.
The really new changes I made are:
~~a) Changed section and variable name percentileValues to postions (as this better reflects the content of the section. Is this ok, or do other modules depend on the exact variable name?~~
b) Every textbook I know begins with mode median mean in this order. JASP reflects this now also in the output table.
c) Sum is a better fit for section distribution
If this commit is accepted I will reorder further items in this module to make it more beginner friendly.
=> restore the "natural order" without renaming percentiles to positions & this time without conflicts

R/descriptives.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1449
So I git blamed my way back into the past and found https://github.com/jasp-stats/jasp-desktop/commit/a22a36809e03a6b86998cceaa526a65b5d5d2291, looks like this function has been incorrectly called for 2 years!
The function that should be called is defined here:
https://github.com/jasp-stats/jaspDescriptives/blob/708c35adc3105eec28b3b8e5080656d5165adc81/R/descriptives.R#L911-L921
The new output is not that super great, but at least it doesn't crash:
basically, each failing subplot shows an error message. In this case, the error messages are also always the same, but in general, it could also be that only 1 subplot shows an error message while the other ones are actually showing a nice plot.
=> Rename function for displaying error message

R/descriptives.R, inst/qml/Descriptives.qml
Fixes https://github.com/jasp-stats/jasp-issues/issues/1480
In this table
the highlighted rows could not be removed. For all other rows, there is an option to remove it. This PR adds two checkboxes so you can also remove those two rows, as requested in the linked issue requested.
=> Make it possible to hide valid and missing

R/descriptives.R, tests/testthat/_snaps/descriptives/dot-plot-large-counts.svg, tests/testthat/test-descriptives.R
Fixes https://github.com/jasp-stats/jasp-issues/issues/1635 and adds a unit test.
The screenshot in the issue nicely shows the problem, the dots are stacked and exceed the y-limits. Now, unfortunately, this is not solved by changing the y-axis limits because geom_dotplot is actually a very terrible geom (see https://github.com/tidyverse/ggplot2/issues/2203). If you change the y-axis limits the plot actually stays the same...
The unit test SVG nicely shows what *should* happen in these cases, namely rescaling the size of the dots.
We could also change the dotplot implementation entirely, but I opted for less severe changes and left my thoughts as a comment in the code.
=> Scale dotplot dotsize with counts

R/descriptives.R
I got annoyed by a lot of code while writing https://github.com/jasp-stats/jaspDescriptives/pull/201 so I did some basic code cleanup. I tried to not refactor anything and do purely stylistic changes. The bulk of the changes was done automatically with:
```r
styler::style_file("R/descriptives.R", scope = "tokens")
```
and then I undid some changes to prevent it from removing intentionally aligned code. We should probably look into doing this a bit more automatically.
Things I changed:
remove calls to `.clean` and `.v`, except for 1 .clean that will be removed in https://github.com/jasp-stats/jaspDescriptives/pull/201
```r
paste($1, sep="") -> paste0($1)
```
```r
substr($1, 1, $2) == $3 -> startsWith($1, $3)
```
```r
if (condition) {
x <- a
} else {
x <- b
}
->
x <- if (condition) {
a
} …
```
=> code cleanup

inst/help/Descriptives_de.md
Hi, here is a German translation of the help text file, in the same format as the English version.
Would this file be automatically shown if the language is set to German, or is some additional change in some code necessary? (The Dutch translation works in my JASP version of 0.17.3.)
=> add German translation of help text

R/descriptives.R
Fixes https://github.com/jasp-stats/jasp-test-release/issues/2518
=> Fix Issue 2518: CI for mean with T model not calculated according to selected width

R/descriptives.R, inst/help/Descriptives.md, inst/help/Descriptives_nl.md, inst/qml/Descriptives.qml, tests/testthat/test-descriptives.R
Preview: 
I was doubting what the best place is for these metrics - they could also be placed in the correlation/regression/reliability module. Also not sure yet about the right naming (e.g., could also remove "Association matrix" and append matrix to covariance and correlation). What do you think @EJWagenmakers and @juliuspfadt?
Related: https://github.com/jasp-stats/jasp-issues/issues/1364
=> Add cov/cor matrices to descriptives

inst/qml/Descriptives.qml
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2530
The LaTex expression is now outside the translatable string. Later we can think of a way to make it easier for the user to add a LaTex expression.
=> LaTex expression broken

R/descriptives.R
other method is pretty wonky for small sample sizes, for instance:
=> Use sturges in customizable histogram

inst/qml/Descriptives.qml
The number of columns can decrease, so set always the columnSpan to the parent.columns
=> Never set the columnSpan explicitly

inst/qml/common/FlexplotForm.qml
Fix https://github.com/jasp-stats/jasp-issues/issues/2750
Also updated the box height to try to visually indicate that only 2 are allowed
New:
=> Fix Flexplot max variable and box height

R/descriptives.R, inst/Description.qml
For https://github.com/jasp-stats/jasp-desktop/pull/5667
=> Use preloadData stuff

R/descriptives.R, jaspDescriptives.Rproj
Broken by @RensDofferhoff in https://github.com/jasp-stats/jaspDescriptives/commit/440f765d025ce9496994665cbe6b150ad2c89d11
preferably next time open a PR so we can see if any unit tests fail :sweat_smile: 
because this is also broken in the current release:
This fix is more of a band-aid until we fully commit to preloadData.
@JohnnyDoorn let me know if you don't have time to review this!
=> Fix density plots

R/descriptives.R, inst/Description.qml, tests/testthat/test-descriptives.R, tests/testthat/test-verified-descriptives.R
Fix https://github.com/jasp-stats/INTERNAL-jasp/issues/2749
Fix https://github.com/jasp-stats/jasp-issues/issues/2846
Fix https://github.com/jasp-stats/jasp-issues/issues/3405
- output is now based on the variable types - min/max/range/quartile/percentile for ordinal, missing/valid for nominal
- removed readdata, use of two data sets (dataset and dataset.factors), most mentions of as.numeric and checking if variables are factors etc. 
- Change verified unit test because footnote about multiple modes was not properly working
- Could not get mixed columns/rows to work (search code for "vandenman" :'-)), so for now there is no type enforcing. Although that does work well as far as I can see, would be better to have it working
The range/min/max still gives weird results for an orderedfactor …
=> respect types and preload data

R/jaspPlotBuilder.R, inst/qml/jaspPlotBuilder.qml
Replaced the histogram script, now using ggplot instead of tidyplot.
Added density plot support, also implemented with ggplot instead of tidyplot.
Added stat ellipse around data points.
Enabled data point size to be mapped to another variable.
Enabled data point shape to be mapped to another variable.
Cleaned up the info code (shortened QML, removed line breaks, no content change).
Fix: https://github.com/jasp-stats/jasp-test-release/issues/2955
Fixed an issue where added text labels sometimes extended beyond the plot (e.g., over the upper y-axis limit). This is now handled better by increasing plot size or adjusting padding/margin.
Made the different geometric layers orderable
=> prerelease fix
